# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pramod Singh
description: >- # this means to ignore newlines until "baseurl:"
  I am Pramod. This is my personal blog where I write about my research, fitness and other things that I find interesting.

baseurl: # the subpath of your site, e.g. /blog
url: https://pramodnegi080.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
github_username: pramodnegi080

ignore_theme_config: true # this means to ignore theme's config _config.yml

# Author Settings
author: Pramod Singh # add your name
author-img: pramod_negi.jpg # add your photo
about-author: >-
  I am a research scholar at Speech Processing Lab, IIIT Hyderabad. I am interested in speech processing, machine learning and deep learning.
  I am a fitness enthusiast and I love to workout.
social-github: Pramodnegi080
social-linkedin: pramod-singh-negi
social-instagram: 

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jemoji
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
